import createHttpError from "http-errors";


export const handleLogout = async (req, res, next) => {
  try {
    
  } catch (err) {
    next(err);
  }
}